### ISSUE TITLE
Unrecognised Date Formats

### ISSUE THREAD

**Issue by lachlan-eagling** [lachlan-eagling/py-strftime#1]
The following date formats return incorrect format codes.

**"11 12 2011"**
.strftime('%m %d 20%m')

**"1900/23/01" or "1900/23/1"**
.strftime('%Y/23/01')

**ISO8601 E.g. "1994-11-05T08:15:30-05:00"**
strftime('%Y-11-05T08:15:30-05:00')

**Comment by lachlan-eagling** [comment]
ISO8601 fixed by ac66af6.

**Comment by alexmojaki** [comment]
On the website at least, an ISO date only doesn't work, e.g. `2020-02-21` gives `.strftime('%d%d-%m-21')`.

**Comment by ceyzeriat** [comment]
on the website too,
"20200904" is incorrect
"04092020" returns month-day-year when it should either fail because of ambiguity or return iso-like day-month-year

**Comment by lachlan-eagling** [comment]
Thanks, @alexmojaki & @ceyzeriat and apologies about the slow response, have had a very busy few weeks.

Expect a fix for these in the coming days.

**Comment by alexmojaki** [comment]
Don't feel bad, this doesn't affect me, just thought I should point it out.
